-- MurlokFury Data File
-- Auto-generated by fetch_murlok.py
-- Source: https://murlok.io/warrior/fury/m+
-- Generated: 2026-02-08T15:35:47Z
-- DO NOT EDIT MANUALLY

MURLOK_DATA = {
    meta = {
        source = "https://murlok.io/warrior/fury/m+",
        updated = "2026-02-08T15:35:47Z",
        sampleSize = 50,
        class = "Warrior",
        spec = "Fury",
        content = "M+",
    },

    heroTalents = {
        { name = "Mountain Thane", count = 47, percent = 88.7 },
        { name = "Slayer", count = 6, percent = 11.3 },
    },

    classTalents = {
        { name = "Berserker Stance", count = 50 },
        { name = "Defensive Stance", count = 50 },
        { name = "War Machine", count = 50 },
        { name = "Impending Victory", count = 50 },
        { name = "Heroic Leap", count = 50 },
        { name = "Rend", count = 50 },
        { name = "Frothing Berserker", count = 50 },
        { name = "Spell Reflection", count = 50 },
        { name = "Armored to the Teeth", count = 50 },
        { name = "Reinforced Plates", count = 50 },
        { name = "Barbaric Training", count = 50 },
        { name = "Cruel Strikes", count = 50 },
        { name = "Dual Wield Specialization", count = 50 },
        { name = "Wild Strikes", count = 50 },
        { name = "Anger Management", count = 50 },
        { name = "Overwhelming Rage", count = 49 },
        { name = "Battlefield Commander", count = 49 },
        { name = "Pain and Gain", count = 48 },
        { name = "Thunder Clap", count = 47 },
        { name = "Double Time", count = 47 },
        { name = "Shockwave", count = 46 },
        { name = "Rallying Cry", count = 44 },
        { name = "Resonant Voice", count = 44 },
        { name = "Crushing Force", count = 44 },
        { name = "Fearless", count = 42 },
        { name = "Honed Reflexes", count = 37 },
        { name = "Storm Bolt", count = 36 },
        { name = "Bounding Stride", count = 30 },
        { name = "Crackling Thunder", count = 19 },
        { name = "Rumbling Earth", count = 14 },
        { name = "Wrecking Throw", count = 12 },
        { name = "Leeching Strikes", count = 9 },
        { name = "Intimidating Shout", count = 9 },
        { name = "Javelineer", count = 6 },
        { name = "Stance Mastery", count = 4 },
        { name = "Interpose", count = 3 },
        { name = "Fast Footwork", count = 1 },
        { name = "Field Dressing", count = 1 },
    },

    specTalents = {
        { name = "Bloodthirst", count = 50 },
        { name = "Raging Blow", count = 50 },
        { name = "Sudden Death", count = 50 },
        { name = "Improved Execute", count = 50 },
        { name = "Fresh Meat", count = 50 },
        { name = "Rampage", count = 50 },
        { name = "Improved Raging Blow", count = 50 },
        { name = "Deep Wounds", count = 50 },
        { name = "Spite", count = 50 },
        { name = "Cruelty", count = 50 },
        { name = "Recklessness", count = 50 },
        { name = "Frenzy", count = 50 },
        { name = "Odyn's Fury", count = 50 },
        { name = "Bloodborne", count = 50 },
        { name = "Reckless Abandon", count = 50 },
        { name = "Focus in Chaos", count = 49 },
        { name = "Executioner's Wrath", count = 49 },
        { name = "Avatar", count = 49 },
        { name = "Frenzied Enrage", count = 47 },
        { name = "Improved Whirlwind", count = 47 },
        { name = "Scent of Blood", count = 47 },
        { name = "Meat Cleaver", count = 47 },
        { name = "Warpaint", count = 46 },
        { name = "Cold Steel, Hot Blood", count = 46 },
        { name = "Deft Experience", count = 46 },
        { name = "Vicious Contempt", count = 46 },
        { name = "Massacre", count = 44 },
        { name = "Enraged Regeneration", count = 18 },
        { name = "Wrath and Fury", count = 5 },
        { name = "Hack and Slash", count = 4 },
        { name = "Critical Thinking", count = 4 },
        { name = "Surge of Adrenaline", count = 4 },
        { name = "Bloodcraze", count = 3 },
    },

    stats = {
        { name = "Haste", percent = 42, avgRating = 471 },
        { name = "Mastery", percent = 64, avgRating = 466 },
        { name = "Versatility", percent = 16, avgRating = 232 },
        { name = "Critical Strike", percent = 19, avgRating = 145 },
    },

    minorStats = {
        { name = "Avoidance", percent = 9, avgRating = 92 },
        { name = "Leech", percent = 4, avgRating = 71 },
        { name = "Speed", percent = 4, avgRating = 0 },
    },

    gear = {
        {
            slot = "Head",
            items = {
                { name = "Living Weapon's Faceshield", count = 32 },
                { name = "Bone-Melted Faceplate", count = 8 },
                { name = "Wing Commander's Helmet", count = 4 },
                { name = "Crown of Absolute Command", count = 2 },
                { name = "Everforged Helm", count = 2 },
            },
        },
        {
            slot = "Neck",
            items = {
                { name = "Chrysalis of Sundered Souls", count = 20 },
                { name = "Cabochon of the Infinite Flight", count = 8 },
                { name = "Momma's Mega Medallion", count = 7 },
                { name = "Amulet of Earthen Craftsmanship", count = 5 },
                { name = "Duskblaze's Desperation", count = 4 },
            },
        },
        {
            slot = "Shoulders",
            items = {
                { name = "Living Weapon's Ramparts", count = 47 },
                { name = "Swarm Monarch's Spaulders", count = 2 },
                { name = "Everforged Pauldrons", count = 1 },
            },
        },
        {
            slot = "Back",
            items = {
                { name = "Reshii Wraps", count = 50 },
            },
        },
        {
            slot = "Chest",
            items = {
                { name = "Living Weapon's Bulwark", count = 49 },
                { name = "Experimental Goresilk Chestguard", count = 1 },
            },
        },
        {
            slot = "Wrist",
            items = {
                { name = "Everforged Vambraces", count = 46 },
                { name = "Living Weapon's Manacles", count = 2 },
                { name = "Yoke of Enveloping Hatred", count = 2 },
            },
        },
        {
            slot = "Hands",
            items = {
                { name = "Living Weapon's Crushers", count = 39 },
                { name = "Everforged Gauntlets", count = 5 },
                { name = "Devourer's Gauntlets", count = 3 },
                { name = "Jumpstarter's Scaffold-Scrapers", count = 2 },
                { name = "Achillite's Unbreakable Grip", count = 1 },
            },
        },
        {
            slot = "Waist",
            items = {
                { name = "Everforged Greatbelt", count = 28 },
                { name = "Fresh Ethereal Fetters", count = 14 },
                { name = "Living Weapon's Chain", count = 6 },
                { name = "Girdle of Somber Ploys", count = 2 },
            },
        },
        {
            slot = "Legs",
            items = {
                { name = "Living Weapon's Legguards", count = 50 },
            },
        },
        {
            slot = "Feet",
            items = {
                { name = "Interloper's Plated Sabatons", count = 47 },
                { name = "Everforged Sabatons", count = 1 },
                { name = "Implacable Weatherproof Treads", count = 1 },
                { name = "Jak'tull's Intruder Stompers", count = 1 },
            },
        },
        {
            slot = "Rings",
            items = {
                { name = "Ring of Earthen Craftsmanship", count = 24 },
                { name = "Signet of the False Accuser", count = 16 },
                { name = "Logic Gate: Omega", count = 15 },
                { name = "Whispers of K'aresh", count = 14 },
                { name = "Radiant Necromancer's Band", count = 11 },
            },
        },
        {
            slot = "Trinkets",
            items = {
                { name = "Astral Antenna", count = 47 },
                { name = "Ara-Kara Sacbrood", count = 30 },
                { name = "Cursed Stone Idol", count = 13 },
                { name = "Improvised Seaforium Pacemaker", count = 5 },
                { name = "Eradicating Arcanocore", count = 4 },
            },
        },
        {
            slot = "Main Hand",
            items = {
                { name = "Photon Sabre Prime", count = 25 },
                { name = "Circuit Breaker", count = 15 },
                { name = "Emberbrand Zweihander", count = 6 },
                { name = "Skyreaver, Greataxe of the Keepers", count = 3 },
                { name = "Fatebound Crusader", count = 1 },
            },
        },
        {
            slot = "Off Hand",
            items = {
                { name = "Photon Sabre Prime", count = 11 },
                { name = "Charged Claymore", count = 10 },
                { name = "Emberbrand Zweihander", count = 9 },
                { name = "Circuit Breaker", count = 8 },
                { name = "Everforged Greataxe", count = 6 },
            },
        },
    },

    enchants = {
        {
            slot = "Head",
            items = {
                { name = "Incandescent Essence", count = 5 },
            },
        },
        {
            slot = "Neck",
            items = {
                { name = "Enchant Neck - Mark of the Hidden Satyr", count = 2 },
            },
        },
        {
            slot = "Shoulders",
            items = {
                { name = "Tiger Fang Inscription", count = 1 },
            },
        },
        {
            slot = "Back",
            items = {
                { name = "Chant of Winged Grace", count = 29 },
                { name = "Chant of Leeching Fangs", count = 15 },
                { name = "+44 Leech", count = 2 },
            },
        },
        {
            slot = "Chest",
            items = {
                { name = "Crystalline Radiance", count = 50 },
            },
        },
        {
            slot = "Wrist",
            items = {
                { name = "+72 Avoidance", count = 34 },
                { name = "+135 Leech", count = 11 },
                { name = "+88 Leech", count = 3 },
            },
        },
        {
            slot = "Hands",
            items = {
                { name = "Enchant Gloves - Super Strength", count = 1 },
                { name = "Enchant Gloves - Zandalari Surveying", count = 1 },
            },
        },
        {
            slot = "Legs",
            items = {
                { name = "Defender's Armor Kit", count = 33 },
                { name = "Stormbound Armor Kit", count = 17 },
            },
        },
        {
            slot = "Feet",
            items = {
                { name = "Defender's March", count = 43 },
                { name = "Scout's March", count = 6 },
                { name = "Enchant Boots - Minor Speed", count = 1 },
            },
        },
        {
            slot = "Rings",
            items = {
                { name = "+21 Mastery", count = 47 },
                { name = "+21 Haste", count = 25 },
                { name = "+21 Versatility", count = 17 },
            },
        },
        {
            slot = "Main Hand",
            items = {
                { name = "Oathsworn's Tenacity", count = 27 },
                { name = "Stonebound Artistry", count = 10 },
                { name = "Stormrider's Fury", count = 8 },
            },
        },
        {
            slot = "Off Hand",
            items = {
                { name = "Oathsworn's Tenacity", count = 34 },
                { name = "Stonebound Artistry", count = 6 },
                { name = "Stormrider's Fury", count = 4 },
            },
        },
    },

    gems = {
        {
            category = "Algari Diamond",
            items = {
                { name = "Culminating Blasphemite", count = 43 },
                { name = "Elusive Blasphemite", count = 6 },
            },
        },
        {
            category = "Fiber",
            items = {
                { name = "Pure Energizing Fiber", count = 25 },
                { name = "Pure Chronomantic Fiber", count = 11 },
                { name = "Pure Dexterous Fiber", count = 9 },
                { name = "Pure Precise Fiber", count = 5 },
            },
        },
        {
            category = "Prismatic",
            items = {
                { name = "Quick Onyx", count = 63 },
                { name = "Versatile Onyx", count = 59 },
                { name = "Versatile Emerald", count = 54 },
                { name = "Masterful Sapphire", count = 52 },
                { name = "Masterful Emerald", count = 46 },
            },
        },
    },

    races = {
        { name = "Night Elf", count = 52, percent = 52.0 },
        { name = "Tauren", count = 10, percent = 10.0 },
        { name = "Dwarf", count = 8, percent = 8.0 },
        { name = "Human", count = 8, percent = 8.0 },
        { name = "Void Elf", count = 8, percent = 8.0 },
        { name = "Blood Elf", count = 4, percent = 4.0 },
        { name = "Dark Iron Dwarf", count = 4, percent = 4.0 },
        { name = "Orc", count = 4, percent = 4.0 },
        { name = "Pandaren", count = 2, percent = 2.0 },
    },
}
